version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - APP_ENV
    command: npm run start:dev
    ports:
      - '3030:3000'
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules/
    #      - ./node_modules:/usr/src/app/node_modules/
    environment:
      APP_ENV: ${APP_ENV}
      APP_PORT: ${APP_PORT}
      DB_HOST: mysqldb
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      JWT_ACCESS_TOKEN_EXP_IN_SEC: ${JWT_ACCESS_TOKEN_EXP_IN_SEC}
      JWT_REFRESH_TOKEN_EXP_IN_SEC: ${JWT_REFRESH_TOKEN_EXP_IN_SEC}
      JWT_PUBLIC_KEY_BASE64: ${JWT_PUBLIC_KEY_BASE64}
      JWT_PRIVATE_KEY_BASE64: ${JWT_PRIVATE_KEY_BASE64}
      DEFAULT_ADMIN_USER_PASSWORD: ${DEFAULT_ADMIN_USER_PASSWORD}
    depends_on:
      - mysqldb
    networks:
      - wlm_net

  mysqldb:
    image: mysql:8
    platform: ${MYSQL_PLATFORM}
    command:
      - --default-authentication-plugin=mysql_native_password
      - --max_connections=2213
    ports:
      - '3336:3306'
    volumes:
      - mysqldata:/var/lib/mysql
      # - ./.config/mysql/master:/etc/mysql/conf.d/
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example_db
    networks:
      - wlm_net

  # mysqldb-slave-1:
  #   image: mysql:8
  #   platform: ${MYSQL_PLATFORM}
  #   command: --default-authentication-plugin=mysql_native_password
  #   ports:
  #     - '3337:3306'
  #   volumes:
  #     - mysqldata-slave-1:/var/lib/mysql
  #     - mysql-slave-log:/var/log/mysql
  #     - ./.config/mysql/slave:/etc/mysql/conf.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_DATABASE: example_db
  #   networks:
  #     - wlm_net
  #   depends_on:
  #     - mysqldb

  # mysqlconfigure:
  #   image: mysql:8
  #   environment:
  #     - 'MYSQL_SLAVE_PASSWORD=example'
  #     - 'MYSQL_MASTER_PASSWORD=example'
  #     - 'MYSQL_ROOT_PASSWORD=example'
  #     - 'MYSQL_REPLICATION_USER=repl'
  #     - 'MYSQL_REPLICATION_PASSWORD=repl'
  #   volumes:
  #     - ./scripts/replication.sh:/tmp/replication.sh
  #   command: /bin/bash -x /tmp/replication.sh
  #   depends_on:
  #     - mysqldb
  #     - mysqldb-slave-1
  #   networks:
  #     - wlm_net

  adminer:
    image: adminer
    ports:
      - '8380:8080'
    depends_on:
      - mysqldb
    networks:
      - wlm_net

  redis:
    image: redis:6-alpine
    ports:
      - 6339:6379
    networks:
      - wlm_net
    volumes:
      - redisdata:/data

volumes:
  node_modules:
  mysqldata:
  redisdata:
  # mysqldata-slave-1:
  # mysql-slave-log:

networks:
  #  walletmessenger_api_wlm_net:
  #  api_wlm_net:
  wlm_net:
    driver: bridge
