export const QUEUE_NAME = {
  WALLET: 'WALLET',
  CHAT: 'CHAT',
  SOCKET: 'WALLET_MESSSENGER_SOCKET',
  ENCRYPT_FILE: 'WALLET_MESSENGER_ENCRYPT_FILE',
};

export const QUEUE_JOB = {
  WALLET: {
    TRANSACTION: 'TRANSACTION',
  },
  CHAT: {
    CREATE_GROUP_CHAT: 'CREATE_GROUP_CHAT',
    CHANGE_GROUP_NAME: 'CHANGE_GROUP_NAME',
    SEND_MESSAGE_TO_GROUP: 'SEND_MESSAGE_TO_GROUP',
    INVITE_MEMBER: 'INVITE_MEMBER',
    ACCEPT_INVITE: 'ACCEPT_INVITE',
    ACCEPT_JOIN_GROUP: 'ACCEPT_JOIN_GROUP',
    ADD_MEMBERS: 'ADD_MEMBERS',
    REMOVE_MEMBERS: 'REMOVE_MEMBERS',
    JOIN_ROOM: 'JOIN_ROOM',
    LEAVE_ROOM: 'LEAVE_ROOM',
    REJECT_JOIN_GROUP: 'REJECT_JOIN_GROUP',
    SET_ADMIN: 'SET_ADMIN',
    REMOVE_ADMIN: 'REMOVE_ADMIN',
    SEND_MESSSAGE_TO_PEER: 'SEND_MESSSAGE_TO_PEER',
    REDEPLOY_GROUP_CHAT: 'REDEPLOY_GROUP_CHAT',
    SEND_RED_PACKET: 'SEND_RED_PACKET',
    PIN_MESSAGE: 'PIN_MESSAGE',
    UNPIN_MESSAGE: 'UNPIN_MESSAGE',
    RETRIVE_MESSAGE: 'RETRIVE_MESSAGE',
  },
  SOCKET: {
    SOCKET: 'SOCKET',
  },
};
